### PR TITLE
Admin - adding logic for expired posts

### PR DESCRIPTION
**Pull request by MarysiaLowas**
I've removed the EXPIRED status as we will need to have some sort of periodic job to find
the expired posts and make them expired. Instead, I moved that logic to the database by
creating two object managers:
1. one extending the model with the "not_expired" field
2. another one returning just the posts which can be displayed on the website (published
and not expired).

The first one is used in django admin for marking visually posts which are expired: the list
views have an additional column and the change_form view displayes the "Expired" label for
expired posts.

The second one is used in views - so we don't repeat ourselves too much.

### CODE REVIEW

**Comment by rebkwok** [comment]
I think this could be more simply achieved just by having an expired() method on the model, without the need for multiple object managers.  Don't set EXPIRED as a status (since the status is really review_status rather than job_status anyway), but have a job.expired() method that just checks the expiry date and returns a boolean.

**Comment by rebkwok** [comment]
Actually, on second thoughts, this is basically what you have done.  I think I'm confusing myself by expecting an expired() method rather than a not_expired().  :)  I'll review better soon

**Comment by MarysiaLowas** [comment]
Well, I've started with creating the is_expired method on the model and using it on the list view in admin but I had problems with making it sortable. Apparently, sorting is done on the db side...

And as for the name ;) it somehow looks better when the not-expired items are listed with the green tick and expired with red dash - that's the reason, I've made it "not_expired". If you think it's counter-intuitive, I can change it the other way round.

**Comment by rebkwok** [comment]
No, the naming is fine

**Pull request merged**
